services:
  - type: web
    name: aurelle-luxury-store
    env: node
    plan: free
    buildCommand: npm install && npm run build
    startCommand: npm run start
    envVars:
      - key: NODE_ENV
        value: production
      - key: PORT
        value: 10000
      - key: JWT_SECRET
        generateValue: true
      - key: ADMIN_EMAIL
        value: admin@aurelle.com
      - key: ADMIN_PASSWORD
        value: AdminAurelle123!
